Added default to switch to stop compiler failure in Chrome (unreviewed)
GrConfigConversionEffect.cpp:33:21: error: enumeration values 'kNone_PMConversion' and 'kPMConversionCnt' not handled in switch [-Werror,-Wswitch]



git-svn-id: http://skia.googlecode.com/svn/trunk@5304 2bbb7eff-a529-9590-31e7-b0007b416f81